### ISSUE TITLE
Feature: Live-reload support for Options page

### ISSUE THREAD

**Issue by heshdotcc** [jfmdev/chrome-extension-popurri#1]
Currently, the only way to see newer changes is closing and reopening such tab.

Anyways, thank you so much for this template!

Cheers,

**Comment by heshdotcc** [comment]
Here may be a possible workaround: https://github.com/d-lowl/chrome-extension-svelte-boilerplate#webpack-auto-reload-and-hrm

**Comment by jfmdev** [comment]
You can run `yarn run watch` and then, after doing your changes, on the Options page you just reload (no need to re-opening).

> I know isn't the same than _hot reloading_ (i.e. the components reloading automatically without having to reload the page), but for know I'm not planning to support that.
